
init__10dSv_save_cFv = 0x8005d860;

item_func_sword__Fv = 0x800c3ad4;
item_func_shield__Fv = 0x800c3b94;
item_func_normal_sail__Fv = 0x800c458c;
item_func_wind_tact__Fv = 0x800c32e0;
item_func_tact_song1__Fv = 0x800c446c;
item_func_tact_song2__Fv = 0x800c449c;
item_func_master_sword__Fv = 0x800c3b14;
item_func_lv3_sword__Fv = 0x800c3b54;
item_func_master_sword_ex__Fv = 0x800c3c54;

onEventBit__11dSv_event_cFUs = 0x8005cb04;
