
PROGRESS_ITEMS = [
  "Picto Box",
  "Spoils Bag",
  "Grappling Hook",
  "Deluxe Picto Box",
  "Hero's Bow",
  "Power Bracelets",
  "Iron Boots",
  "Bait Bag",
  "Boomerang",
  "Hookshot",
  "Delivery Bag",
  "Bombs",
  "Skull Hammer",
  "Deku Leaf",
  "Fire and Ice Arrows",
  "Light Arrow",
  "Master Sword (Powerless)",
  "Master Sword (Half power)",
  "Mirror Shield",
  "Master Sword (Full power)",
  
  "Triforce Shard 1",
  "Triforce Shard 2",
  "Triforce Shard 3",
  "Triforce Shard 4",
  "Triforce Shard 5",
  "Triforce Shard 6",
  "Triforce Shard 7",
  "Triforce Shard 8",
  
  "Nayru's Pearl",
  "Din's Pearl",
  "Farore's Pearl",
  
  "Ballad of Gales",
  "Command Melody",
  "Earth God's Lyric",
  "Wind God's Aria",
  "Song of Passing",
  
  "All-Purpose Bait",
  "Hyoi Pear",
  
  "Town Flower",
  
  "Father's Letter",
  "Note to Mom",
  "Maggie's Letter",
  "Moblin's Letter",
  "Cabana Deed",
  
  "1000 Rupee Wallet",
  "5000 Rupee Wallet",
  
  "Ghost Ship Chart",
  
  "Triforce Chart 8",
  "Triforce Chart 7",
  "Triforce Chart 6",
  "Triforce Chart 5",
  "Triforce Chart 4",
  "Triforce Chart 3",
  "Triforce Chart 2",
  "Triforce Chart 1",
] + ["Empty Bottle"]*4

NONPROGRESS_ITEMS = [
  "Telescope",
  "Tingle Tuner",
  "Magic Armor",
  "Hero's Charm",

  "Complimentary ID",
  "Fill-Up Coupon",

  "Dragon Tingle Statue",
  "Forbidden Tingle Statue",
  "Goddess Tingle Statue",
  "Earth Tingle Statue",
  "Wind Tingle Statue",

  "Hurricane Spin",

  "60 Bomb Bomb Bag",
  "99 Bomb Bomb Bag",
  "60 Arrow Quiver",
  "99 Arrow Quiver",

  "Submarine Chart",
  "Beedle's Chart",
  "Platform Chart",
  "Light Ring Chart",
  "Secret Cave Chart",
  "Sea Hearts Chart",
  "Island Hearts Chart",
  "Great Fairy Chart",
  "Octo Chart",
  "IN-credible Chart",
  
  "Treasure Chart 7",
  "Treasure Chart 27",
  "Treasure Chart 21",
  "Treasure Chart 13",
  "Treasure Chart 32",
  "Treasure Chart 19",
  "Treasure Chart 41",
  "Treasure Chart 26",
  "Treasure Chart 8",
  "Treasure Chart 37",
  "Treasure Chart 25",
  "Treasure Chart 17",
  "Treasure Chart 36",
  "Treasure Chart 22",
  "Treasure Chart 9",

  "Tingle's Chart",

  "Treasure Chart 14",
  "Treasure Chart 10",
  "Treasure Chart 40",
  "Treasure Chart 3",
  "Treasure Chart 4",
  "Treasure Chart 28",
  "Treasure Chart 16",
  "Treasure Chart 18",
  "Treasure Chart 34",
  "Treasure Chart 29",
  "Treasure Chart 1",
  "Treasure Chart 35",
  "Treasure Chart 12",
  "Treasure Chart 6",
  "Treasure Chart 24",
  "Treasure Chart 39",
  "Treasure Chart 38",
  "Treasure Chart 2",
  "Treasure Chart 33",
  "Treasure Chart 31",
  "Treasure Chart 23",
  "Treasure Chart 5",
  "Treasure Chart 20",
  "Treasure Chart 30",
  "Treasure Chart 15",
  "Treasure Chart 11",
] + ["Piece of Heart"]*44 + ["Heart Container"]*6

CONSUMABLE_ITEMS = [
  "Green Rupee",
  "Blue Rupee",
  "Yellow Rupee",
  "Red Rupee",
  "Purple Rupee",
  "Orange Rupee",
  "Silver Rupee",

  "Joy Pendant",
  "Skull Necklace",
  "Boko Baba Seed",
  "Golden Feather",
  "Knight's Crest",
  "Red Chu Jelly",
  "Green Chu Jelly",
  "Blue Chu Jelly",
]
